"""The engine wire contract, generated from ``typewriter/spec.yaml``.

``vocab`` holds the stdlib-only vocabularies; ``models`` holds the pydantic wire
models. Both are generated by ``scripts/gen_typewriter.py`` and never edited.
"""
