"""The engine's wire models and per-kind feature models.

Generated by scripts/gen_typewriter.py from typewriter/spec.yaml. DO NOT EDIT:
change the spec and run ``make typewriter``.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


class StuckRequest(BaseModel):
    task_id: str | None = None
    features: dict[str, float] | None = None


class StuckResponse(BaseModel):
    probability: float
    confidence: str


class WorkflowStateRequest(BaseModel):
    task_id: str | None = None
    classified_events: list[dict[str, Any]] | None = None


class WorkflowStateResponse(BaseModel):
    flow_state: dict[str, float]
    dominant_state: str
    momentum: float
    focus_score: float
    dominant_activity: str
    activity_distribution: dict[str, float]
    session_elapsed_min: float
    method: str
    confidence: float


class DurationRequest(BaseModel):
    task_id: str | None = None
    features: dict[str, float] | None = None


class DurationResponse(BaseModel):
    estimated_minutes: float
    confidence_interval: list[float]


class QualityRequest(BaseModel):
    features: dict[str, float]


class QualityResponse(BaseModel):
    score: int
    components: dict[str, float]
    status: str


class TrainRequest(BaseModel):
    db: str | None = Field(None, description="Deprecated: ignored, kept for backward compat")


class TrainResponse(BaseModel):
    status: str
    message: str


class ModelHealth(BaseModel):
    """Per-model health detail (WP05). ``refusal`` carries the registry's refusal text."""

    status: str = Field(..., description="Same value as HealthResponse.models[name].")
    slot: str | None = Field(..., description='Registry slot serving it: "local" | "base" | "cold_start" | null.')
    refusal: str | None = Field(..., description="Registry refusal reason text (integrity/contract/runtime), or null.")


class LayaEligibility(BaseModel):
    """The per-host laya eligibility verdict (laya-serving-and-packs-01MSK2SP WP03, FR-005).

    Measured **lazily** at the first dispatch of a laya-configured kind, so a
    fresh boot reports ``verdict: "not_evaluated"`` with null measurements until
    then (honest nulls, never invented -- the ``ModelIntrospection`` discipline).
    ``/health`` never triggers the benchmark. ``measured_against`` is ``"fixture"``
    when no checkpoint exists to measure (the bundled non-functional
    random-weights fixture): those timings say little about a real checkpoint.
    """

    verdict: str = Field(..., description='"eligible" | "ineligible" | "not_evaluated".')
    reason: str = Field(
        ..., description="Stable code: eligible, insufficient_memory, memory_unknown, benchmark_failed, ..."
    )
    detail: str
    measured_against: str | None = Field(..., description='"fixture" | "checkpoint" | null when unmeasured.')
    free_memory_bytes: int | None
    memory_method: str | None
    benchmark_calls: int | None
    p50_ms: float | None
    p95_ms: float | None
    max_ms: float | None
    evaluated_at_ms: int | None


class HealthResponse(BaseModel):
    """``/health`` — honest enough for a client to verify (FR-016, Amendment A1).

    The pre-existing fields are unchanged (C-008; ``models`` stays name ->
    status string). Every field added by two-client-engine-01MSK2EN is
    **required**: the model cannot be built from ``{}`` or a partial payload, so
    a bare or legacy response is structurally distinguishable from this one.
    ``exe_path`` is reported truthfully and never verified here — verification
    is the client's job (FR-017, C-001).
    """

    status: str
    # Default for backward compatibility
    mode: str = "local"
    models: dict[str, str]
    uptime_sec: float
    product: str = Field(
        ..., description='Always "kenaz-ml" (the product name; the frozen artifact keeps its own frozen name).'
    )
    sidecar_version: str
    contract_versions: dict[str, list[str]] = Field(
        ..., description="Per recommend kind, the feature_contract_version values /v1/recommend accepts."
    )
    exe_path: str = Field(..., description="This process's own resolved executable path; not self-verified.")
    engine_sha256: str | None = Field(
        ...,
        description="sha256 of the engine's own executable file (sys.executable resolved through symlinks; the launcher executable in the frozen onedir), computed once at startup. An adoption cross-check for the client, never a trust root; null only if the file could not be read.",
    )
    model_details: dict[str, ModelHealth] = Field(..., description="Per-model status with registry refusal text.")
    device: str = Field(..., description='Compute device; "cpu" for the scikit-learn engine.')
    lifecycle_protocol: int = Field(
        ..., description="Lifecycle protocol version: 1 = speaks /v1/clients/lease; 0 = none (cloud mode, legacy)."
    )
    laya_eligibility: LayaEligibility = Field(
        ...,
        description="The per-host laya eligibility verdict (laya-serving-and-packs-01MSK2SP WP03): the one field that mission adds to this schema. An ineligible host refuses laya-bearing kinds; the client falls back.",
    )


class LeaseRequest(BaseModel):
    client: str = Field(..., min_length=1)
    pid: int = Field(..., gt=0)
    client_version: str
    min_contracts: dict[str, str] = Field(
        default_factory=dict,
        description="Per kind, the feature_contract_version this client requires. Only reported back (incompatible_kinds); never stops the engine serving other clients.",
    )


class LeaseResponse(BaseModel):
    lifecycle_protocol: int
    sidecar_version: str
    contract_versions: dict[str, list[str]]
    incompatible_kinds: dict[str, str] = Field(..., description="kind -> why this client's min_contracts is unmet.")
    client: str
    pid: int
    live_leases: int
    implicit_lease_sec: float
    idle_exit_sec: float
    managed: bool = Field(..., description="True when the install root's lease/ directory exists.")


class ShutdownResponse(BaseModel):
    status: str


class ModelIntrospection(BaseModel):
    """Per-model metadata for the /introspect endpoint.

    Honesty contract (kenaz spec 060): fields the sidecar does not track
    today are returned as null/zero — never invented.
    """

    name: str
    display_name: str
    # ml_predictions.model value this model's predictions are written under (per the WAL contract:
    # "stuck"|"suggest"|"duration"|"quality"|"profile"), or null for models that never write
    # predictions directly.
    prediction_model: str | None = None
    # Underlying sklearn estimator class name, "rules" for rule-based models, or null when the model
    # object is not loaded.
    algorithm: str | None = None
    # Mirrors /health: "ready" | "untrained" | "not_loaded".
    status: str
    trained: bool
    # ISO-8601 UTC timestamp of the last persisted weights write (file mtime via LocalModelStore), or
    # null when untracked/never trained.
    last_trained: str | None = None
    # Training sample count is not tracked per-model today — always null.
    sample_count: int | None = None
    # Count of this model's non-expired ml_predictions rows from the last 24h.
    recent_predictions: int = 0
    # No per-predictor toggle exists today (capabilities.toggle=false); reflects whether the model is
    # loaded and will serve predictions.
    enabled: bool
    # Registry provenance (two-client-engine-01MSK2EN WP01, additive). Which registry slot served this
    # model: "local" | "base" | "cold_start", or null when the model is not resolved through the
    # registry (quality, whose JSON weights the registry cannot govern; or a non-filesystem store).
    serving_slot: str | None = None
    # The serving manifest's provenance.training_source ("local" | "base" | ...), or null when no
    # manifest served (cold start / not registry-resolved).
    training_source: str | None = None
    # The serving manifest's version (Manifest.version), or null.
    manifest_version: str | None = None
    # Registry refusal text collected while resolving ("<model> [<slot>] <check>/<reason>: <detail>";
    # empty-slot misses omitted), or null when nothing was refused.
    refusal: str | None = None


class IntrospectResponse(BaseModel):
    service: str
    version: str
    mode: str
    uptime_sec: float
    models: list[ModelIntrospection]
    # Capability discovery for kenaz (spec 060 FR-008): controls are hidden in the UI when the
    # capability is absent, rather than erroring.
    capabilities: dict[str, bool]


class RecommendRequest(BaseModel):
    """``POST /v1/recommend/{kind}`` body (design doc §3.2)."""

    features: dict[str, float] = Field(..., description="Feature values keyed by name; must match the kind's contract.")
    feature_contract_version: str = Field(..., description="The contract version the client computed features under.")
    session_id: str | None = Field(None, description="Opaque client session id; not interpreted by the engine.")
    kind_id: str | None = Field(None, description="Optional; when present it must equal the path's kind.")
    # Exact shadow-join key (ruled 2026-09-30): the same (features_hash, ts) the client later pushes
    # on the label row. Optional and absent-tolerated; the engine never interprets them for serving.
    features_hash: str | None = Field(
        None, min_length=1, description="Optional: the label row's features_hash for this decision (exact shadow join)."
    )
    ts: int | None = Field(
        None, gt=0, description="Optional: the label row's ts (decision time, epoch ms) for this decision."
    )


class RecommendResponse(BaseModel):
    """A served recommendation (FR-004). Exactly one of ``decision``/``score``.

    Field semantics for values the specs leave open:

    * ``rung`` — the serving manifest's ``metrics["rung"]`` when present,
      otherwise the backend name (a test fixture reports ``"heuristic"``).
    * ``checkpoint_provenance`` — the registry slot that served the artifact
      (``local`` / ``base``); ``org`` is reserved for an org-distributed pack.
      A test fixture has no checkpoint and reports ``local`` (in-process).
    * ``model_id_sha8`` — first eight hex characters of the serving artifact's
      ``artifact_sha256``; ``null`` when there is no artifact (a fixture).
    * ``generation`` — the serving manifest's ``Manifest.version``; ``"0"`` when
      there is no artifact.
    * ``unbenchmarked`` — ``true`` unless the manifest records
      ``metrics["benchmarked"] is True``; always ``true`` for a fixture.
    """

    decision: bool | None = None
    score: int | None = None
    confidence: int = Field(..., ge=0, le=100, description="0-100, validated, never clamped.")
    kind_id: str
    feature_contract_version: str
    model: str
    rung: str
    backend: Literal["heuristic", "classic", "laya"]
    model_id_sha8: str | None
    checkpoint_provenance: Literal["local", "org", "base"]
    generation: str
    unbenchmarked: bool

    @model_validator(mode="after")
    def _exactly_one_answer(self) -> RecommendResponse:
        if (self.decision is not None) + (self.score is not None) != 1:
            raise ValueError("exactly one of decision or score must be set")
        return self


class RefusalBody(BaseModel):
    kind_id: str
    reason: str = Field(..., description="Stable machine reason, e.g. kind_not_served, contract_mismatch.")
    detail: str = Field(..., description="Human-readable diagnostic, e.g. 'kind unavailable: contract v3 != v2'.")


class RecommendRefusal(BaseModel):
    """Every typed refusal: HTTP :data:`REFUSAL_STATUS_CODE`, this body.

    ``error`` is the stable machine code at the top level — the envelope the
    harness's ``mlsidecar`` client parses (``{"error": "<code>"}``; a code of
    ``kind_not_served`` satisfies its ``ErrKindNotServed``). ``refusal`` repeats
    it with the kind and a human-readable detail.
    """

    error: str = Field(..., description="Stable typed code, e.g. kind_not_served, contract_mismatch.")
    refusal: RefusalBody


class ContractEntry(BaseModel):
    """One kind in ``GET /v1/contracts``, keyed by kind id in :class:`ContractsResponse`.

    ``features``/``backend``/``available`` are the fields the harness's
    ``KindContract`` reads; ``available`` is true only when a backend actually
    serves the kind (the harness gates routing on it). ``version`` is the
    kind's 16-hex contract version (D-A4).
    """

    features: list[str] = Field(..., description="Ordered feature names (the vector layout).")
    dtypes: list[str]
    version: str
    supported_versions: list[str] = Field(
        ..., description="Versions accepted by /v1/recommend. Only the current one today (no N-1 defined)."
    )
    available: bool
    backend: str | None = None
    reason: str | None = None
    detail: str | None = None


class ContractsResponse(BaseModel):
    kinds: dict[str, ContractEntry] = Field(..., description="Every registered kind, keyed by kind id.")


class LabelCursor(BaseModel):
    """The ack cursor: a position over ``(ts, revision)``."""

    ts: int
    revision: int


class LabelRow(BaseModel):
    """One ``advice_labels`` row, in the harness's wire shape (``mlsidecar.LabelWireRow``).

    Frozen contract (Amendment A3.3): idempotency key
    ``(client, kind, features_hash, ts)``; ``ts`` is the row's original
    creation time and never changes across revisions; ``revision`` is the
    harness's table-global monotonic change counter, and a higher one replaces
    the stored row (equal or lower is stale). Propensity fields are kept
    verbatim in the kind's label log; only ``accepted`` / ``auto_acted`` (y=1)
    and ``dismissed`` (y=0) rows with ``features_complete=true`` reach the
    retained training set. There is deliberately no ``session_id``.
    """

    kind: str
    features_hash: str
    ts: int = Field(..., description="The row's original created_at (ms); part of the key, never changes.")
    revision: int = Field(..., ge=0, description="Table-global monotonic change counter; higher replaces.")
    features: dict[str, Any] | str = Field(
        default_factory=dict, description="Feature values keyed by name (a JSON object, or its JSON text)."
    )
    features_complete: bool
    shown: bool
    decision: bool | None = None
    confidence: int | None = Field(None, description="Confidence at decision time (0-100).")
    model: str | None = Field(None, description="The model that answered (the harness's model_id).")
    rung: str | None = None
    prompt_version: str | None = None
    user_action: str = Field(..., description="accepted | dismissed | ignored | auto_acted")
    latency_ms: float | None = None
    client: str | None = Field(None, description="Optional; defaults to the batch's client.")
    feature_contract_version: str | None = Field(
        None, description="Optional; when present it must equal the kind's published contract version."
    )
    snapshot_ms: int | None = Field(
        None, description="Optional feature snapshot time (ms); ts is used when absent. Carried, never recomputed."
    )


class LabelBatchRequest(BaseModel):
    client: str
    rows: list[LabelRow]


class LabelRowRefusal(BaseModel):
    index: int
    features_hash: str
    ts: int
    revision: int
    reason: str


class LabelBatchResponse(BaseModel):
    """``applied`` = new keys, ``replaced`` = higher-revision upserts, ``stale`` = not newer.

    ``acked`` is the ``(ts, revision)`` of the last row of the batch, in the
    order sent — always a row of this batch (never beyond the pushed window).
    Per-row refusals are permanent (no re-send can fix them), so the ack
    advances past them; each is listed in ``refusals`` (Amendment A4). A
    batch-level failure (409 / 413 / 503) acks nothing. ``null`` only for an
    empty batch.
    """

    acked: LabelCursor | None
    applied: int
    replaced: int
    stale: int
    refused: int
    refusals: list[LabelRowRefusal]
    retained_appended: int
    retained_rebuilt: bool
    retained_generation: str | None = None


class FeatureEvent(BaseModel):
    """One pushed feature event. Validated per event by ``features_push`` so a bad
    event never fails its batch; the loose types here are deliberate.
    """

    event_class: Any = Field(
        ...,
        description='Closed registry: "commit" (specified); egress_deny, run_outcome, budget_pressure, lifecycle (schema-deferred, refused).',
    )
    ts_ms: Any = Field(..., description="Event time, positive integer milliseconds (for commit: the commit time).")
    session_id: Any = Field(None, description="Scopes the event; omitted = global.")
    fields: Any = Field(default_factory=dict, description="Class-specific fields; must be empty for commit.")


class FeaturesPushRequest(BaseModel):
    client: str
    events: list[FeatureEvent]


class FeatureEventRefusal(BaseModel):
    index: int
    reason: str
    detail: str


class FeaturesPushResponse(BaseModel):
    accepted: int
    refused: int
    refusals: list[FeatureEventRefusal]


class LaneRefusalBody(BaseModel):
    reason: str
    detail: str


class LaneRefusal(BaseModel):
    error: str
    refusal: LaneRefusalBody


class BranchNowFeatures(BaseModel):
    """The ``branch_now`` feature vector, in contract order. Should the session branch now?

    The wire carries these as a name -> number object (``RecommendRequest.features``);
    this model is the typed form of that object.
    """

    model_config = ConfigDict(extra="forbid")

    turns_since_session_start: float
    turns_since_last_branch: float
    prior_branch_count: float
    edit_resend_precursor: float
    heuristic_signal_count: float
    heuristic_noise_count: float
    last_user_msg_len: float
    tool_call_density_window: float


class CompactNowFeatures(BaseModel):
    """The ``compact_now`` feature vector, in contract order. Should the session compact its context now?

    The wire carries these as a name -> number object (``RecommendRequest.features``);
    this model is the typed form of that object.
    """

    model_config = ConfigDict(extra="forbid")

    context_fill_fraction: float
    tokens_in_span: float
    turns_since_last_compaction: float
    tool_result_token_fraction: float
    model_context_limit: float
    historical_compression_ratio: float


class EscalateModelFeatures(BaseModel):
    """The ``escalate_model`` feature vector, in contract order. Should the session escalate to a stronger model?

    The wire carries these as a name -> number object (``RecommendRequest.features``);
    this model is the typed form of that object.
    """

    model_config = ConfigDict(extra="forbid")

    consecutive_tool_failures: float
    retries_in_window: float
    turn_latency_trend: float
    current_rung: float
    error_kind_auth: float
    error_kind_transient: float
    error_kind_cancelled: float
    error_kind_budget: float
    error_kind_unknown: float
    budget_remaining_fraction: float


class RightSizeModelFeatures(BaseModel):
    """The ``right_size_model`` feature vector, in contract order. Should the session move to a smaller model, stay, or move to a larger one? Three-way (SizingDirection); served hosted, trained per member from harness turn outcomes (hosted-advice-right-size-model-01M4HQ0A).

    The wire carries these as a name -> number object (``RecommendRequest.features``);
    this model is the typed form of that object.
    """

    model_config = ConfigDict(extra="forbid")

    consecutive_tool_failures: float
    retries_in_window: float
    turn_latency_trend: float
    current_rung: float
    error_kind_auth: float
    error_kind_transient: float
    error_kind_cancelled: float
    error_kind_budget: float
    error_kind_unknown: float
    budget_remaining_fraction: float
    context_fill_fraction: float
    tokens_in_bucket: float
    tokens_out_bucket: float
    tool_calls: float
    followup_continue: float
    followup_edit_resend: float
    followup_regenerate: float
    followup_stop: float
    followup_branch: float
    followup_none: float
    model_class_small: float
    model_class_medium: float
    model_class_large: float
    model_class_unknown: float


# Kind id -> its feature model.
KIND_FEATURE_MODELS: dict[str, type[BaseModel]] = {
    "branch_now": BranchNowFeatures,
    "compact_now": CompactNowFeatures,
    "escalate_model": EscalateModelFeatures,
    "right_size_model": RightSizeModelFeatures,
}

# Every wire schema, by name.
SCHEMAS: dict[str, type[BaseModel]] = {
    "StuckRequest": StuckRequest,
    "StuckResponse": StuckResponse,
    "WorkflowStateRequest": WorkflowStateRequest,
    "WorkflowStateResponse": WorkflowStateResponse,
    "DurationRequest": DurationRequest,
    "DurationResponse": DurationResponse,
    "QualityRequest": QualityRequest,
    "QualityResponse": QualityResponse,
    "TrainRequest": TrainRequest,
    "TrainResponse": TrainResponse,
    "ModelHealth": ModelHealth,
    "LayaEligibility": LayaEligibility,
    "HealthResponse": HealthResponse,
    "LeaseRequest": LeaseRequest,
    "LeaseResponse": LeaseResponse,
    "ShutdownResponse": ShutdownResponse,
    "ModelIntrospection": ModelIntrospection,
    "IntrospectResponse": IntrospectResponse,
    "RecommendRequest": RecommendRequest,
    "RecommendResponse": RecommendResponse,
    "RefusalBody": RefusalBody,
    "RecommendRefusal": RecommendRefusal,
    "ContractEntry": ContractEntry,
    "ContractsResponse": ContractsResponse,
    "LabelCursor": LabelCursor,
    "LabelRow": LabelRow,
    "LabelBatchRequest": LabelBatchRequest,
    "LabelRowRefusal": LabelRowRefusal,
    "LabelBatchResponse": LabelBatchResponse,
    "FeatureEvent": FeatureEvent,
    "FeaturesPushRequest": FeaturesPushRequest,
    "FeatureEventRefusal": FeatureEventRefusal,
    "FeaturesPushResponse": FeaturesPushResponse,
    "LaneRefusalBody": LaneRefusalBody,
    "LaneRefusal": LaneRefusal,
    "BranchNowFeatures": BranchNowFeatures,
    "CompactNowFeatures": CompactNowFeatures,
    "EscalateModelFeatures": EscalateModelFeatures,
    "RightSizeModelFeatures": RightSizeModelFeatures,
}
