"""The engine's shared vocabularies: kinds, ordered features and closed enums.

Generated by scripts/gen_typewriter.py from typewriter/spec.yaml. DO NOT EDIT:
change the spec and run ``make typewriter``.
"""

from __future__ import annotations

# Standard library only: kenaz_ml.advice.contracts imports this module (NFR-001).

VOCABULARY_VERSION = 1

FEATURE_DTYPE = "float64"

# The client's closed error-category enum, in order. A category unknown at the wire buckets to
# `unknown`. Changing it requires a vocabulary_version bump.
ERROR_KINDS: tuple[str, ...] = (
    "auth",
    "transient",
    "cancelled",
    "budget",
    "unknown",
)

# A right_size_model answer: move to a smaller model, stay, or move to a larger one.
SIZING_DIRECTIONS: tuple[str, ...] = (
    "down",
    "stay",
    "up",
)

# The coarse size class of the model a turn ran on, from a fixed harness mapping of its catalog. Never
# a model id or provider.
MODEL_CLASSS: tuple[str, ...] = (
    "small",
    "medium",
    "large",
)

# What the member did after the previous turn; `none` when the session ended or went idle first. A
# followup unknown at the wire buckets to `none`.
TURN_FOLLOWUPS: tuple[str, ...] = (
    "continue",
    "edit_resend",
    "regenerate",
    "stop",
    "branch",
    "none",
)

# What the user did with a recommendation. `accepted` and `auto_acted` train as y=1, `dismissed` as
# y=0; `ignored` is recorded but never trained.
USER_ACTIONS: tuple[str, ...] = (
    "accepted",
    "dismissed",
    "ignored",
    "auto_acted",
)

# The closed serving-backend set. `heuristic` is reserved for test fixtures: the engine ships no
# heuristic backends.
BACKENDS: tuple[str, ...] = (
    "heuristic",
    "classic",
    "laya",
)

# The registry slot that served the artifact.
CHECKPOINT_PROVENANCES: tuple[str, ...] = (
    "local",
    "org",
    "base",
)

# Stable machine reasons for a typed /v1/recommend refusal.
RECOMMEND_REFUSAL_REASONS: tuple[str, ...] = (
    "unknown_kind",
    "kind_not_served",
    "laya_backend_not_installed",
    "contract_mismatch",
    "features_mismatch",
    "features_invalid",
    "kind_id_mismatch",
    "backend_unknown",
    "no_contract",
    "confidence_out_of_range",
    "backend_error",
    "host_ineligible",
    "checkpoint_refused",
)

# Batch-level /v1/labels refusals. Nothing is written and nothing is acked.
LABEL_BATCH_REFUSAL_REASONS: tuple[str, ...] = (
    "contract_mismatch",
    "names_mismatch",
    "retained_refused",
    "io_error",
)

# Per-row /v1/labels refusals. Each is permanent (no re-send can fix the row), so the ack advances
# past it.
LABEL_ROW_REFUSAL_REASONS: tuple[str, ...] = (
    "unknown_user_action",
    "client_mismatch",
    "kind_mismatch",
    "features_invalid",
    "row_too_large",
)

# Refusal reasons on the /v1/features push lane.
FEATURES_REFUSAL_REASONS: tuple[str, ...] = (
    "unknown_class",
    "class_schema_not_defined",
    "invalid_ts_ms",
    "invalid_fields",
    "invalid_session_id",
    "batch_too_large",
    "lane_unavailable",
)

# Kind id -> ordered feature names. The order is the vector layout.
KIND_FEATURES: dict[str, tuple[str, ...]] = {
    "branch_now": (
        "turns_since_session_start",
        "turns_since_last_branch",
        "prior_branch_count",
        "edit_resend_precursor",
        "heuristic_signal_count",
        "heuristic_noise_count",
        "last_user_msg_len",
        "tool_call_density_window",
    ),
    "compact_now": (
        "context_fill_fraction",
        "tokens_in_span",
        "turns_since_last_compaction",
        "tool_result_token_fraction",
        "model_context_limit",
        "historical_compression_ratio",
    ),
    "escalate_model": (
        "consecutive_tool_failures",
        "retries_in_window",
        "turn_latency_trend",
        "current_rung",
        "error_kind_auth",
        "error_kind_transient",
        "error_kind_cancelled",
        "error_kind_budget",
        "error_kind_unknown",
        "budget_remaining_fraction",
    ),
    "right_size_model": (
        "consecutive_tool_failures",
        "retries_in_window",
        "turn_latency_trend",
        "current_rung",
        "error_kind_auth",
        "error_kind_transient",
        "error_kind_cancelled",
        "error_kind_budget",
        "error_kind_unknown",
        "budget_remaining_fraction",
        "context_fill_fraction",
        "tokens_in_bucket",
        "tokens_out_bucket",
        "tool_calls",
        "followup_continue",
        "followup_edit_resend",
        "followup_regenerate",
        "followup_stop",
        "followup_branch",
        "followup_none",
        "model_class_small",
        "model_class_medium",
        "model_class_large",
    ),
}

# Kind id -> the 16-hex contract version a client sends as feature_contract_version.
KIND_CONTRACT_VERSIONS: dict[str, str] = {
    "branch_now": "20e0d23994daee80",
    "compact_now": "3ad8b0c1fa514476",
    "escalate_model": "57d4bdc1bd6a71be",
    "right_size_model": "573b80ba4cca078d",
}
