// Code generated by scripts/gen_typewriter.py from spec.yaml. DO NOT EDIT.

// Package typewriter is the kenaz-ml engine's wire contract: the request and
// response shapes, the recommendation kinds with their ordered feature
// vectors, and the closed vocabularies. It is generated from spec.yaml in
// the kenaz-ml repository, the same file the engine's own models come from.
package typewriter

import "encoding/json"

// VocabularyVersion is the semantic salt folded into every contract version.
const VocabularyVersion = 1

// FeatureDtype is the dtype every kind feature is declared with.
const FeatureDtype = "float64"

// ErrorKind: The client's closed error-category enum, in order. A category
// unknown at the wire buckets to `unknown`. Changing it requires a
// vocabulary_version bump.
type ErrorKind string

const (
	ErrorKindAuth      ErrorKind = "auth"
	ErrorKindTransient ErrorKind = "transient"
	ErrorKindCancelled ErrorKind = "cancelled"
	ErrorKindBudget    ErrorKind = "budget"
	ErrorKindUnknown   ErrorKind = "unknown"
)

// ErrorKinds lists every ErrorKind, in spec order.
var ErrorKinds = []ErrorKind{
	ErrorKindAuth,
	ErrorKindTransient,
	ErrorKindCancelled,
	ErrorKindBudget,
	ErrorKindUnknown,
}

// UserAction: What the user did with a recommendation. `accepted` and
// `auto_acted` train as y=1, `dismissed` as y=0; `ignored` is recorded but
// never trained.
type UserAction string

const (
	UserActionAccepted  UserAction = "accepted"
	UserActionDismissed UserAction = "dismissed"
	UserActionIgnored   UserAction = "ignored"
	UserActionAutoActed UserAction = "auto_acted"
)

// UserActions lists every UserAction, in spec order.
var UserActions = []UserAction{
	UserActionAccepted,
	UserActionDismissed,
	UserActionIgnored,
	UserActionAutoActed,
}

// Backend: The closed serving-backend set. `heuristic` is reserved for test
// fixtures: the engine ships no heuristic backends.
type Backend string

const (
	BackendHeuristic Backend = "heuristic"
	BackendClassic   Backend = "classic"
	BackendLaya      Backend = "laya"
)

// Backends lists every Backend, in spec order.
var Backends = []Backend{
	BackendHeuristic,
	BackendClassic,
	BackendLaya,
}

// CheckpointProvenance: The registry slot that served the artifact.
type CheckpointProvenance string

const (
	CheckpointProvenanceLocal CheckpointProvenance = "local"
	CheckpointProvenanceOrg   CheckpointProvenance = "org"
	CheckpointProvenanceBase  CheckpointProvenance = "base"
)

// CheckpointProvenances lists every CheckpointProvenance, in spec order.
var CheckpointProvenances = []CheckpointProvenance{
	CheckpointProvenanceLocal,
	CheckpointProvenanceOrg,
	CheckpointProvenanceBase,
}

// RecommendRefusalReason: Stable machine reasons for a typed /v1/recommend
// refusal.
type RecommendRefusalReason string

const (
	RecommendRefusalReasonUnknownKind             RecommendRefusalReason = "unknown_kind"
	RecommendRefusalReasonKindNotServed           RecommendRefusalReason = "kind_not_served"
	RecommendRefusalReasonLayaBackendNotInstalled RecommendRefusalReason = "laya_backend_not_installed"
	RecommendRefusalReasonContractMismatch        RecommendRefusalReason = "contract_mismatch"
	RecommendRefusalReasonFeaturesMismatch        RecommendRefusalReason = "features_mismatch"
	RecommendRefusalReasonFeaturesInvalid         RecommendRefusalReason = "features_invalid"
	RecommendRefusalReasonKindIDMismatch          RecommendRefusalReason = "kind_id_mismatch"
	RecommendRefusalReasonBackendUnknown          RecommendRefusalReason = "backend_unknown"
	RecommendRefusalReasonNoContract              RecommendRefusalReason = "no_contract"
	RecommendRefusalReasonConfidenceOutOfRange    RecommendRefusalReason = "confidence_out_of_range"
	RecommendRefusalReasonBackendError            RecommendRefusalReason = "backend_error"
	RecommendRefusalReasonHostIneligible          RecommendRefusalReason = "host_ineligible"
	RecommendRefusalReasonCheckpointRefused       RecommendRefusalReason = "checkpoint_refused"
)

// RecommendRefusalReasons lists every RecommendRefusalReason, in spec order.
var RecommendRefusalReasons = []RecommendRefusalReason{
	RecommendRefusalReasonUnknownKind,
	RecommendRefusalReasonKindNotServed,
	RecommendRefusalReasonLayaBackendNotInstalled,
	RecommendRefusalReasonContractMismatch,
	RecommendRefusalReasonFeaturesMismatch,
	RecommendRefusalReasonFeaturesInvalid,
	RecommendRefusalReasonKindIDMismatch,
	RecommendRefusalReasonBackendUnknown,
	RecommendRefusalReasonNoContract,
	RecommendRefusalReasonConfidenceOutOfRange,
	RecommendRefusalReasonBackendError,
	RecommendRefusalReasonHostIneligible,
	RecommendRefusalReasonCheckpointRefused,
}

// LabelBatchRefusalReason: Batch-level /v1/labels refusals. Nothing is written
// and nothing is acked.
type LabelBatchRefusalReason string

const (
	LabelBatchRefusalReasonContractMismatch LabelBatchRefusalReason = "contract_mismatch"
	LabelBatchRefusalReasonNamesMismatch    LabelBatchRefusalReason = "names_mismatch"
	LabelBatchRefusalReasonRetainedRefused  LabelBatchRefusalReason = "retained_refused"
	LabelBatchRefusalReasonIOError          LabelBatchRefusalReason = "io_error"
)

// LabelBatchRefusalReasons lists every LabelBatchRefusalReason, in spec order.
var LabelBatchRefusalReasons = []LabelBatchRefusalReason{
	LabelBatchRefusalReasonContractMismatch,
	LabelBatchRefusalReasonNamesMismatch,
	LabelBatchRefusalReasonRetainedRefused,
	LabelBatchRefusalReasonIOError,
}

// LabelRowRefusalReason: Per-row /v1/labels refusals. Each is permanent (no
// re-send can fix the row), so the ack advances past it.
type LabelRowRefusalReason string

const (
	LabelRowRefusalReasonUnknownUserAction LabelRowRefusalReason = "unknown_user_action"
	LabelRowRefusalReasonClientMismatch    LabelRowRefusalReason = "client_mismatch"
	LabelRowRefusalReasonKindMismatch      LabelRowRefusalReason = "kind_mismatch"
	LabelRowRefusalReasonFeaturesInvalid   LabelRowRefusalReason = "features_invalid"
	LabelRowRefusalReasonRowTooLarge       LabelRowRefusalReason = "row_too_large"
)

// LabelRowRefusalReasons lists every LabelRowRefusalReason, in spec order.
var LabelRowRefusalReasons = []LabelRowRefusalReason{
	LabelRowRefusalReasonUnknownUserAction,
	LabelRowRefusalReasonClientMismatch,
	LabelRowRefusalReasonKindMismatch,
	LabelRowRefusalReasonFeaturesInvalid,
	LabelRowRefusalReasonRowTooLarge,
}

// FeaturesRefusalReason: Refusal reasons on the /v1/features push lane.
type FeaturesRefusalReason string

const (
	FeaturesRefusalReasonUnknownClass          FeaturesRefusalReason = "unknown_class"
	FeaturesRefusalReasonClassSchemaNotDefined FeaturesRefusalReason = "class_schema_not_defined"
	FeaturesRefusalReasonInvalidTSMS           FeaturesRefusalReason = "invalid_ts_ms"
	FeaturesRefusalReasonInvalidFields         FeaturesRefusalReason = "invalid_fields"
	FeaturesRefusalReasonInvalidSessionID      FeaturesRefusalReason = "invalid_session_id"
	FeaturesRefusalReasonBatchTooLarge         FeaturesRefusalReason = "batch_too_large"
	FeaturesRefusalReasonLaneUnavailable       FeaturesRefusalReason = "lane_unavailable"
)

// FeaturesRefusalReasons lists every FeaturesRefusalReason, in spec order.
var FeaturesRefusalReasons = []FeaturesRefusalReason{
	FeaturesRefusalReasonUnknownClass,
	FeaturesRefusalReasonClassSchemaNotDefined,
	FeaturesRefusalReasonInvalidTSMS,
	FeaturesRefusalReasonInvalidFields,
	FeaturesRefusalReasonInvalidSessionID,
	FeaturesRefusalReasonBatchTooLarge,
	FeaturesRefusalReasonLaneUnavailable,
}

// Recommendation kind ids.
const (
	KindBranchNow     = "branch_now"
	KindCompactNow    = "compact_now"
	KindEscalateModel = "escalate_model"
)

// KindIDs lists every kind, in publication order.
var KindIDs = []string{KindBranchNow, KindCompactNow, KindEscalateModel}

// ContractVersions maps a kind to the 16-hex contract version this build
// was generated against: the value to send as feature_contract_version.
var ContractVersions = map[string]string{
	KindBranchNow:     BranchNowContractVersion,
	KindCompactNow:    CompactNowContractVersion,
	KindEscalateModel: EscalateModelContractVersion,
}

// FeatureNames maps a kind to its ordered feature names (the vector layout).
var FeatureNames = map[string][]string{
	KindBranchNow:     BranchNowFeatureNames,
	KindCompactNow:    CompactNowFeatureNames,
	KindEscalateModel: EscalateModelFeatureNames,
}

// BranchNowContractVersion is the branch_now contract version.
const BranchNowContractVersion = "20e0d23994daee80"

// BranchNowFeatureNames is the branch_now vector layout.
var BranchNowFeatureNames = []string{
	"turns_since_session_start",
	"turns_since_last_branch",
	"prior_branch_count",
	"edit_resend_precursor",
	"heuristic_signal_count",
	"heuristic_noise_count",
	"last_user_msg_len",
	"tool_call_density_window",
}

// BranchNowFeatures is the branch_now feature vector, in contract order.
// Should the session branch now?
type BranchNowFeatures struct {
	TurnsSinceSessionStart float64 `json:"turns_since_session_start"`
	TurnsSinceLastBranch   float64 `json:"turns_since_last_branch"`
	PriorBranchCount       float64 `json:"prior_branch_count"`
	EditResendPrecursor    float64 `json:"edit_resend_precursor"`
	HeuristicSignalCount   float64 `json:"heuristic_signal_count"`
	HeuristicNoiseCount    float64 `json:"heuristic_noise_count"`
	LastUserMsgLen         float64 `json:"last_user_msg_len"`
	ToolCallDensityWindow  float64 `json:"tool_call_density_window"`
}

// Map returns the features keyed by name, the shape RecommendRequest.Features carries.
func (f BranchNowFeatures) Map() map[string]float64 {
	return map[string]float64{
		"turns_since_session_start": f.TurnsSinceSessionStart,
		"turns_since_last_branch":   f.TurnsSinceLastBranch,
		"prior_branch_count":        f.PriorBranchCount,
		"edit_resend_precursor":     f.EditResendPrecursor,
		"heuristic_signal_count":    f.HeuristicSignalCount,
		"heuristic_noise_count":     f.HeuristicNoiseCount,
		"last_user_msg_len":         f.LastUserMsgLen,
		"tool_call_density_window":  f.ToolCallDensityWindow,
	}
}

// Vector returns the features positionally, in contract order.
func (f BranchNowFeatures) Vector() []float64 {
	return []float64{f.TurnsSinceSessionStart, f.TurnsSinceLastBranch, f.PriorBranchCount, f.EditResendPrecursor, f.HeuristicSignalCount, f.HeuristicNoiseCount, f.LastUserMsgLen, f.ToolCallDensityWindow}
}

// CompactNowContractVersion is the compact_now contract version.
const CompactNowContractVersion = "3ad8b0c1fa514476"

// CompactNowFeatureNames is the compact_now vector layout.
var CompactNowFeatureNames = []string{
	"context_fill_fraction",
	"tokens_in_span",
	"turns_since_last_compaction",
	"tool_result_token_fraction",
	"model_context_limit",
	"historical_compression_ratio",
}

// CompactNowFeatures is the compact_now feature vector, in contract order.
// Should the session compact its context now?
type CompactNowFeatures struct {
	ContextFillFraction        float64 `json:"context_fill_fraction"`
	TokensInSpan               float64 `json:"tokens_in_span"`
	TurnsSinceLastCompaction   float64 `json:"turns_since_last_compaction"`
	ToolResultTokenFraction    float64 `json:"tool_result_token_fraction"`
	ModelContextLimit          float64 `json:"model_context_limit"`
	HistoricalCompressionRatio float64 `json:"historical_compression_ratio"`
}

// Map returns the features keyed by name, the shape RecommendRequest.Features carries.
func (f CompactNowFeatures) Map() map[string]float64 {
	return map[string]float64{
		"context_fill_fraction":        f.ContextFillFraction,
		"tokens_in_span":               f.TokensInSpan,
		"turns_since_last_compaction":  f.TurnsSinceLastCompaction,
		"tool_result_token_fraction":   f.ToolResultTokenFraction,
		"model_context_limit":          f.ModelContextLimit,
		"historical_compression_ratio": f.HistoricalCompressionRatio,
	}
}

// Vector returns the features positionally, in contract order.
func (f CompactNowFeatures) Vector() []float64 {
	return []float64{f.ContextFillFraction, f.TokensInSpan, f.TurnsSinceLastCompaction, f.ToolResultTokenFraction, f.ModelContextLimit, f.HistoricalCompressionRatio}
}

// EscalateModelContractVersion is the escalate_model contract version.
const EscalateModelContractVersion = "57d4bdc1bd6a71be"

// EscalateModelFeatureNames is the escalate_model vector layout.
var EscalateModelFeatureNames = []string{
	"consecutive_tool_failures",
	"retries_in_window",
	"turn_latency_trend",
	"current_rung",
	"error_kind_auth",
	"error_kind_transient",
	"error_kind_cancelled",
	"error_kind_budget",
	"error_kind_unknown",
	"budget_remaining_fraction",
}

// EscalateModelFeatures is the escalate_model feature vector, in contract
// order. Should the session escalate to a stronger model?
type EscalateModelFeatures struct {
	ConsecutiveToolFailures float64 `json:"consecutive_tool_failures"`
	RetriesInWindow         float64 `json:"retries_in_window"`
	TurnLatencyTrend        float64 `json:"turn_latency_trend"`
	CurrentRung             float64 `json:"current_rung"`
	ErrorKindAuth           float64 `json:"error_kind_auth"`
	ErrorKindTransient      float64 `json:"error_kind_transient"`
	ErrorKindCancelled      float64 `json:"error_kind_cancelled"`
	ErrorKindBudget         float64 `json:"error_kind_budget"`
	ErrorKindUnknown        float64 `json:"error_kind_unknown"`
	BudgetRemainingFraction float64 `json:"budget_remaining_fraction"`
}

// Map returns the features keyed by name, the shape RecommendRequest.Features carries.
func (f EscalateModelFeatures) Map() map[string]float64 {
	return map[string]float64{
		"consecutive_tool_failures": f.ConsecutiveToolFailures,
		"retries_in_window":         f.RetriesInWindow,
		"turn_latency_trend":        f.TurnLatencyTrend,
		"current_rung":              f.CurrentRung,
		"error_kind_auth":           f.ErrorKindAuth,
		"error_kind_transient":      f.ErrorKindTransient,
		"error_kind_cancelled":      f.ErrorKindCancelled,
		"error_kind_budget":         f.ErrorKindBudget,
		"error_kind_unknown":        f.ErrorKindUnknown,
		"budget_remaining_fraction": f.BudgetRemainingFraction,
	}
}

// Vector returns the features positionally, in contract order.
func (f EscalateModelFeatures) Vector() []float64 {
	return []float64{f.ConsecutiveToolFailures, f.RetriesInWindow, f.TurnLatencyTrend, f.CurrentRung, f.ErrorKindAuth, f.ErrorKindTransient, f.ErrorKindCancelled, f.ErrorKindBudget, f.ErrorKindUnknown, f.BudgetRemainingFraction}
}

// StuckRequest is a wire schema of the engine.
type StuckRequest struct {
	TaskID   *string            `json:"task_id,omitempty"`
	Features map[string]float64 `json:"features,omitempty"`
}

// StuckResponse is a wire schema of the engine.
type StuckResponse struct {
	Probability float64 `json:"probability"`
	Confidence  string  `json:"confidence"`
}

// WorkflowStateRequest is a wire schema of the engine.
type WorkflowStateRequest struct {
	TaskID           *string          `json:"task_id,omitempty"`
	ClassifiedEvents []map[string]any `json:"classified_events,omitempty"`
}

// WorkflowStateResponse is a wire schema of the engine.
type WorkflowStateResponse struct {
	FlowState            map[string]float64 `json:"flow_state"`
	DominantState        string             `json:"dominant_state"`
	Momentum             float64            `json:"momentum"`
	FocusScore           float64            `json:"focus_score"`
	DominantActivity     string             `json:"dominant_activity"`
	ActivityDistribution map[string]float64 `json:"activity_distribution"`
	SessionElapsedMin    float64            `json:"session_elapsed_min"`
	Method               string             `json:"method"`
	Confidence           float64            `json:"confidence"`
}

// DurationRequest is a wire schema of the engine.
type DurationRequest struct {
	TaskID   *string            `json:"task_id,omitempty"`
	Features map[string]float64 `json:"features,omitempty"`
}

// DurationResponse is a wire schema of the engine.
type DurationResponse struct {
	EstimatedMinutes   float64   `json:"estimated_minutes"`
	ConfidenceInterval []float64 `json:"confidence_interval"`
}

// QualityRequest is a wire schema of the engine.
type QualityRequest struct {
	Features map[string]float64 `json:"features"`
}

// QualityResponse is a wire schema of the engine.
type QualityResponse struct {
	Score      int64              `json:"score"`
	Components map[string]float64 `json:"components"`
	Status     string             `json:"status"`
}

// TrainRequest is a wire schema of the engine.
type TrainRequest struct {
	// Deprecated: ignored, kept for backward compat
	Db *string `json:"db,omitempty"`
}

// TrainResponse is a wire schema of the engine.
type TrainResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

// ModelHealth: Per-model health detail (WP05). `refusal` carries the
// registry's refusal text.
type ModelHealth struct {
	// Same value as HealthResponse.models[name].
	Status string `json:"status"`

	// Registry slot serving it: "local" | "base" | "cold_start" | null.
	Slot *string `json:"slot"`

	// Registry refusal reason text (integrity/contract/runtime), or null.
	Refusal *string `json:"refusal"`
}

// LayaEligibility: The per-host laya eligibility verdict (laya-serving-and-
// packs-01MSK2SP WP03, FR-005).
//
// Measured **lazily** at the first dispatch of a laya-configured kind, so a
// fresh boot reports `verdict: "not_evaluated"` with null measurements until
// then (honest nulls, never invented -- the `ModelIntrospection` discipline).
// `/health` never triggers the benchmark. `measured_against` is `"fixture"`
// when no checkpoint exists to measure (the bundled non-functional random-
// weights fixture): those timings say little about a real checkpoint.
type LayaEligibility struct {
	// "eligible" | "ineligible" | "not_evaluated".
	Verdict string `json:"verdict"`

	// Stable code: eligible, insufficient_memory, memory_unknown,
	// benchmark_failed, ...
	Reason string `json:"reason"`
	Detail string `json:"detail"`

	// "fixture" | "checkpoint" | null when unmeasured.
	MeasuredAgainst *string  `json:"measured_against"`
	FreeMemoryBytes *int64   `json:"free_memory_bytes"`
	MemoryMethod    *string  `json:"memory_method"`
	BenchmarkCalls  *int64   `json:"benchmark_calls"`
	P50MS           *float64 `json:"p50_ms"`
	P95MS           *float64 `json:"p95_ms"`
	MaxMS           *float64 `json:"max_ms"`
	EvaluatedAtMS   *int64   `json:"evaluated_at_ms"`
}

// HealthResponse: `/health` — honest enough for a client to verify (FR-016,
// Amendment A1).
//
// The pre-existing fields are unchanged (C-008; `models` stays name -> status
// string). Every field added by two-client-engine-01MSK2EN is **required**:
// the model cannot be built from `{}` or a partial payload, so a bare or
// legacy response is structurally distinguishable from this one. `exe_path` is
// reported truthfully and never verified here — verification is the client's
// job (FR-017, C-001).
type HealthResponse struct {
	Status string `json:"status"`

	// Default for backward compatibility
	Mode      string            `json:"mode"`
	Models    map[string]string `json:"models"`
	UptimeSec float64           `json:"uptime_sec"`

	// Always "kenaz-ml" (the product name; the frozen artifact keeps its own
	// frozen name).
	Product        string `json:"product"`
	SidecarVersion string `json:"sidecar_version"`

	// Per recommend kind, the feature_contract_version values /v1/recommend
	// accepts.
	ContractVersions map[string][]string `json:"contract_versions"`

	// This process's own resolved executable path; not self-verified.
	ExePath string `json:"exe_path"`

	// sha256 of the engine's own executable file (sys.executable resolved through
	// symlinks; the launcher executable in the frozen onedir), computed once at
	// startup. An adoption cross-check for the client, never a trust root; null
	// only if the file could not be read.
	EngineSHA256 *string `json:"engine_sha256"`

	// Per-model status with registry refusal text.
	ModelDetails map[string]ModelHealth `json:"model_details"`

	// Compute device; "cpu" for the scikit-learn engine.
	Device string `json:"device"`

	// Lifecycle protocol version: 1 = speaks /v1/clients/lease; 0 = none (cloud
	// mode, legacy).
	LifecycleProtocol int64 `json:"lifecycle_protocol"`

	// The per-host laya eligibility verdict (laya-serving-and-packs-01MSK2SP
	// WP03): the one field that mission adds to this schema. An ineligible host
	// refuses laya-bearing kinds; the client falls back.
	LayaEligibility LayaEligibility `json:"laya_eligibility"`
}

// LeaseRequest is a wire schema of the engine.
type LeaseRequest struct {
	Client        string `json:"client"`
	PID           int64  `json:"pid"`
	ClientVersion string `json:"client_version"`

	// Per kind, the feature_contract_version this client requires. Only reported
	// back (incompatible_kinds); never stops the engine serving other clients.
	MinContracts map[string]string `json:"min_contracts,omitempty"`
}

// LeaseResponse is a wire schema of the engine.
type LeaseResponse struct {
	LifecycleProtocol int64               `json:"lifecycle_protocol"`
	SidecarVersion    string              `json:"sidecar_version"`
	ContractVersions  map[string][]string `json:"contract_versions"`

	// kind -> why this client's min_contracts is unmet.
	IncompatibleKinds map[string]string `json:"incompatible_kinds"`
	Client            string            `json:"client"`
	PID               int64             `json:"pid"`
	LiveLeases        int64             `json:"live_leases"`
	ImplicitLeaseSec  float64           `json:"implicit_lease_sec"`
	IdleExitSec       float64           `json:"idle_exit_sec"`

	// True when the install root's lease/ directory exists.
	Managed bool `json:"managed"`
}

// ShutdownResponse is a wire schema of the engine.
type ShutdownResponse struct {
	Status string `json:"status"`
}

// ModelIntrospection: Per-model metadata for the /introspect endpoint.
//
// Honesty contract (kenaz spec 060): fields the sidecar does not track today
// are returned as null/zero — never invented.
type ModelIntrospection struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`

	// ml_predictions.model value this model's predictions are written under (per
	// the WAL contract: "stuck"|"suggest"|"duration"|"quality"|"profile"), or
	// null for models that never write predictions directly.
	PredictionModel *string `json:"prediction_model,omitempty"`

	// Underlying sklearn estimator class name, "rules" for rule-based models, or
	// null when the model object is not loaded.
	Algorithm *string `json:"algorithm,omitempty"`

	// Mirrors /health: "ready" | "untrained" | "not_loaded".
	Status  string `json:"status"`
	Trained bool   `json:"trained"`

	// ISO-8601 UTC timestamp of the last persisted weights write (file mtime via
	// LocalModelStore), or null when untracked/never trained.
	LastTrained *string `json:"last_trained,omitempty"`

	// Training sample count is not tracked per-model today — always null.
	SampleCount *int64 `json:"sample_count,omitempty"`

	// Count of this model's non-expired ml_predictions rows from the last 24h.
	RecentPredictions int64 `json:"recent_predictions"`

	// No per-predictor toggle exists today (capabilities.toggle=false); reflects
	// whether the model is loaded and will serve predictions.
	Enabled bool `json:"enabled"`

	// Registry provenance (two-client-engine-01MSK2EN WP01, additive). Which
	// registry slot served this model: "local" | "base" | "cold_start", or null
	// when the model is not resolved through the registry (quality, whose JSON
	// weights the registry cannot govern; or a non-filesystem store).
	ServingSlot *string `json:"serving_slot,omitempty"`

	// The serving manifest's provenance.training_source ("local" | "base" | ...),
	// or null when no manifest served (cold start / not registry-resolved).
	TrainingSource *string `json:"training_source,omitempty"`

	// The serving manifest's version (Manifest.version), or null.
	ManifestVersion *string `json:"manifest_version,omitempty"`

	// Registry refusal text collected while resolving ("<model> [<slot>]
	// <check>/<reason>: <detail>"; empty-slot misses omitted), or null when
	// nothing was refused.
	Refusal *string `json:"refusal,omitempty"`
}

// IntrospectResponse is a wire schema of the engine.
type IntrospectResponse struct {
	Service   string               `json:"service"`
	Version   string               `json:"version"`
	Mode      string               `json:"mode"`
	UptimeSec float64              `json:"uptime_sec"`
	Models    []ModelIntrospection `json:"models"`

	// Capability discovery for kenaz (spec 060 FR-008): controls are hidden in
	// the UI when the capability is absent, rather than erroring.
	Capabilities map[string]bool `json:"capabilities"`
}

// RecommendRequest: `POST /v1/recommend/{kind}` body (design doc §3.2).
type RecommendRequest struct {
	// Feature values keyed by name; must match the kind's contract.
	Features map[string]float64 `json:"features"`

	// The contract version the client computed features under.
	FeatureContractVersion string `json:"feature_contract_version"`

	// Opaque client session id; not interpreted by the engine.
	SessionID *string `json:"session_id,omitempty"`

	// Optional; when present it must equal the path's kind.
	KindID *string `json:"kind_id,omitempty"`

	// Optional: the label row's features_hash for this decision (exact shadow
	// join).
	//
	// Exact shadow-join key (ruled 2026-09-30): the same (features_hash, ts) the
	// client later pushes on the label row. Optional and absent-tolerated; the
	// engine never interprets them for serving.
	FeaturesHash *string `json:"features_hash,omitempty"`

	// Optional: the label row's ts (decision time, epoch ms) for this decision.
	TS *int64 `json:"ts,omitempty"`
}

// RecommendResponse: A served recommendation (FR-004). Exactly one of
// `decision`/`score`.
//
// Field semantics for values the specs leave open:
//
//   - `rung` — the serving manifest's `metrics["rung"]` when present,
//     otherwise the backend name (a test fixture reports `"heuristic"`).
//   - `checkpoint_provenance` — the registry slot that served the artifact
//     (`local` / `base`); `org` is reserved for an org-distributed pack.
//     A test fixture has no checkpoint and reports `local` (in-process).
//   - `model_id_sha8` — first eight hex characters of the serving artifact's
//     `artifact_sha256`; `null` when there is no artifact (a fixture).
//   - `generation` — the serving manifest's `Manifest.version`; `"0"` when
//     there is no artifact.
//   - `unbenchmarked` — `true` unless the manifest records
//     `metrics["benchmarked"] is True`; always `true` for a fixture.
type RecommendResponse struct {
	Decision *bool  `json:"decision,omitempty"`
	Score    *int64 `json:"score,omitempty"`

	// 0-100, validated, never clamped.
	Confidence             int64                `json:"confidence"`
	KindID                 string               `json:"kind_id"`
	FeatureContractVersion string               `json:"feature_contract_version"`
	Model                  string               `json:"model"`
	Rung                   string               `json:"rung"`
	Backend                Backend              `json:"backend"`
	ModelIDSHA8            *string              `json:"model_id_sha8"`
	CheckpointProvenance   CheckpointProvenance `json:"checkpoint_provenance"`
	Generation             string               `json:"generation"`
	Unbenchmarked          bool                 `json:"unbenchmarked"`
}

// RefusalBody is a wire schema of the engine.
type RefusalBody struct {
	KindID string `json:"kind_id"`

	// Stable machine reason, e.g. kind_not_served, contract_mismatch.
	//
	// One of the RecommendRefusalReason values.
	Reason string `json:"reason"`

	// Human-readable diagnostic, e.g. 'kind unavailable: contract v3 != v2'.
	Detail string `json:"detail"`
}

// RecommendRefusal: Every typed refusal: HTTP :data:`REFUSAL_STATUS_CODE`,
// this body.
//
// `error` is the stable machine code at the top level — the envelope the
// harness's `mlsidecar` client parses (`{"error": "<code>"}`; a code of
// `kind_not_served` satisfies its `ErrKindNotServed`). `refusal` repeats it
// with the kind and a human-readable detail.
type RecommendRefusal struct {
	// Stable typed code, e.g. kind_not_served, contract_mismatch.
	//
	// One of the RecommendRefusalReason values.
	Error   string      `json:"error"`
	Refusal RefusalBody `json:"refusal"`
}

// ContractEntry: One kind in `GET /v1/contracts`, keyed by kind id in
// :class:`ContractsResponse`.
//
// `features`/`backend`/`available` are the fields the harness's `KindContract`
// reads; `available` is true only when a backend actually serves the kind (the
// harness gates routing on it). `version` is the kind's 16-hex contract
// version (D-A4).
type ContractEntry struct {
	// Ordered feature names (the vector layout).
	Features []string `json:"features"`
	Dtypes   []string `json:"dtypes"`
	Version  string   `json:"version"`

	// Versions accepted by /v1/recommend. Only the current one today (no N-1
	// defined).
	SupportedVersions []string `json:"supported_versions"`
	Available         bool     `json:"available"`

	// One of the Backend values.
	Backend *string `json:"backend,omitempty"`
	Reason  *string `json:"reason,omitempty"`
	Detail  *string `json:"detail,omitempty"`
}

// ContractsResponse is a wire schema of the engine.
type ContractsResponse struct {
	// Every registered kind, keyed by kind id.
	Kinds map[string]ContractEntry `json:"kinds"`
}

// LabelCursor: The ack cursor: a position over `(ts, revision)`.
type LabelCursor struct {
	TS       int64 `json:"ts"`
	Revision int64 `json:"revision"`
}

// LabelRow: One `advice_labels` row, in the harness's wire shape
// (`mlsidecar.LabelWireRow`).
//
// Frozen contract (Amendment A3.3): idempotency key `(client, kind,
// features_hash, ts)`; `ts` is the row's original creation time and never
// changes across revisions; `revision` is the harness's table-global monotonic
// change counter, and a higher one replaces the stored row (equal or lower is
// stale). Propensity fields are kept verbatim in the kind's label log; only
// `accepted` / `auto_acted` (y=1) and `dismissed` (y=0) rows with
// `features_complete=true` reach the retained training set. There is
// deliberately no `session_id`.
type LabelRow struct {
	Kind         string `json:"kind"`
	FeaturesHash string `json:"features_hash"`

	// The row's original created_at (ms); part of the key, never changes.
	TS int64 `json:"ts"`

	// Table-global monotonic change counter; higher replaces.
	Revision int64 `json:"revision"`

	// Feature values keyed by name (a JSON object, or its JSON text).
	Features         json.RawMessage `json:"features,omitempty"`
	FeaturesComplete bool            `json:"features_complete"`
	Shown            bool            `json:"shown"`
	Decision         *bool           `json:"decision,omitempty"`

	// Confidence at decision time (0-100).
	Confidence *int64 `json:"confidence,omitempty"`

	// The model that answered (the harness's model_id).
	Model         *string `json:"model,omitempty"`
	Rung          *string `json:"rung,omitempty"`
	PromptVersion *string `json:"prompt_version,omitempty"`

	// accepted | dismissed | ignored | auto_acted
	//
	// One of the UserAction values.
	UserAction string   `json:"user_action"`
	LatencyMS  *float64 `json:"latency_ms,omitempty"`

	// Optional; defaults to the batch's client.
	Client *string `json:"client,omitempty"`

	// Optional; when present it must equal the kind's published contract version.
	FeatureContractVersion *string `json:"feature_contract_version,omitempty"`

	// Optional feature snapshot time (ms); ts is used when absent. Carried, never
	// recomputed.
	SnapshotMS *int64 `json:"snapshot_ms,omitempty"`
}

// LabelBatchRequest is a wire schema of the engine.
type LabelBatchRequest struct {
	Client string     `json:"client"`
	Rows   []LabelRow `json:"rows"`
}

// LabelRowRefusal is a wire schema of the engine.
type LabelRowRefusal struct {
	Index        int64  `json:"index"`
	FeaturesHash string `json:"features_hash"`
	TS           int64  `json:"ts"`
	Revision     int64  `json:"revision"`

	// One of the LabelRowRefusalReason values.
	Reason string `json:"reason"`
}

// LabelBatchResponse: `applied` = new keys, `replaced` = higher-revision
// upserts, `stale` = not newer.
//
// `acked` is the `(ts, revision)` of the last row of the batch, in the order
// sent — always a row of this batch (never beyond the pushed window). Per-row
// refusals are permanent (no re-send can fix them), so the ack advances past
// them; each is listed in `refusals` (Amendment A4). A batch-level failure
// (409 / 413 / 503) acks nothing. `null` only for an empty batch.
type LabelBatchResponse struct {
	Acked              *LabelCursor      `json:"acked"`
	Applied            int64             `json:"applied"`
	Replaced           int64             `json:"replaced"`
	Stale              int64             `json:"stale"`
	Refused            int64             `json:"refused"`
	Refusals           []LabelRowRefusal `json:"refusals"`
	RetainedAppended   int64             `json:"retained_appended"`
	RetainedRebuilt    bool              `json:"retained_rebuilt"`
	RetainedGeneration *string           `json:"retained_generation,omitempty"`
}

// FeatureEvent: One pushed feature event. Validated per event by
// `features_push` so a bad event never fails its batch; the loose types here
// are deliberate.
type FeatureEvent struct {
	// Closed registry: "commit" (specified); egress_deny, run_outcome,
	// budget_pressure, lifecycle (schema-deferred, refused).
	EventClass any `json:"event_class"`

	// Event time, positive integer milliseconds (for commit: the commit time).
	TSMS any `json:"ts_ms"`

	// Scopes the event; omitted = global.
	SessionID any `json:"session_id,omitempty"`

	// Class-specific fields; must be empty for commit.
	Fields any `json:"fields,omitempty"`
}

// FeaturesPushRequest is a wire schema of the engine.
type FeaturesPushRequest struct {
	Client string         `json:"client"`
	Events []FeatureEvent `json:"events"`
}

// FeatureEventRefusal is a wire schema of the engine.
type FeatureEventRefusal struct {
	Index int64 `json:"index"`

	// One of the FeaturesRefusalReason values.
	Reason string `json:"reason"`
	Detail string `json:"detail"`
}

// FeaturesPushResponse is a wire schema of the engine.
type FeaturesPushResponse struct {
	Accepted int64                 `json:"accepted"`
	Refused  int64                 `json:"refused"`
	Refusals []FeatureEventRefusal `json:"refusals"`
}

// LaneRefusalBody is a wire schema of the engine.
type LaneRefusalBody struct {
	// One of the FeaturesRefusalReason values.
	Reason string `json:"reason"`
	Detail string `json:"detail"`
}

// LaneRefusal is a wire schema of the engine.
type LaneRefusal struct {
	// One of the FeaturesRefusalReason values.
	Error   string          `json:"error"`
	Refusal LaneRefusalBody `json:"refusal"`
}

// Schemas constructs an empty value of every wire schema, by name.
var Schemas = map[string]func() any{
	"StuckRequest":          func() any { return new(StuckRequest) },
	"StuckResponse":         func() any { return new(StuckResponse) },
	"WorkflowStateRequest":  func() any { return new(WorkflowStateRequest) },
	"WorkflowStateResponse": func() any { return new(WorkflowStateResponse) },
	"DurationRequest":       func() any { return new(DurationRequest) },
	"DurationResponse":      func() any { return new(DurationResponse) },
	"QualityRequest":        func() any { return new(QualityRequest) },
	"QualityResponse":       func() any { return new(QualityResponse) },
	"TrainRequest":          func() any { return new(TrainRequest) },
	"TrainResponse":         func() any { return new(TrainResponse) },
	"ModelHealth":           func() any { return new(ModelHealth) },
	"LayaEligibility":       func() any { return new(LayaEligibility) },
	"HealthResponse":        func() any { return new(HealthResponse) },
	"LeaseRequest":          func() any { return new(LeaseRequest) },
	"LeaseResponse":         func() any { return new(LeaseResponse) },
	"ShutdownResponse":      func() any { return new(ShutdownResponse) },
	"ModelIntrospection":    func() any { return new(ModelIntrospection) },
	"IntrospectResponse":    func() any { return new(IntrospectResponse) },
	"RecommendRequest":      func() any { return new(RecommendRequest) },
	"RecommendResponse":     func() any { return new(RecommendResponse) },
	"RefusalBody":           func() any { return new(RefusalBody) },
	"RecommendRefusal":      func() any { return new(RecommendRefusal) },
	"ContractEntry":         func() any { return new(ContractEntry) },
	"ContractsResponse":     func() any { return new(ContractsResponse) },
	"LabelCursor":           func() any { return new(LabelCursor) },
	"LabelRow":              func() any { return new(LabelRow) },
	"LabelBatchRequest":     func() any { return new(LabelBatchRequest) },
	"LabelRowRefusal":       func() any { return new(LabelRowRefusal) },
	"LabelBatchResponse":    func() any { return new(LabelBatchResponse) },
	"FeatureEvent":          func() any { return new(FeatureEvent) },
	"FeaturesPushRequest":   func() any { return new(FeaturesPushRequest) },
	"FeatureEventRefusal":   func() any { return new(FeatureEventRefusal) },
	"FeaturesPushResponse":  func() any { return new(FeaturesPushResponse) },
	"LaneRefusalBody":       func() any { return new(LaneRefusalBody) },
	"LaneRefusal":           func() any { return new(LaneRefusal) },
	"BranchNowFeatures":     func() any { return new(BranchNowFeatures) },
	"CompactNowFeatures":    func() any { return new(CompactNowFeatures) },
	"EscalateModelFeatures": func() any { return new(EscalateModelFeatures) },
}
